CREATE DATABASE IF NOT EXISTS fastapi;

CREATE USER IF NOT EXISTS 'hdk'@'%' IDENTIFIED BY 'hdk';
GRANT ALL PRIVILEGES ON fastapi.* TO 'hdk'@'%' WITH GRANT OPTION;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;